version: '3'

services:
  docs:
    image: spm_task_local_docs
    container_name: spm_task_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./spm_task:/app/spm_task:z
    ports:
      - '9000:9000'
    command: /start-docs
